base_url = "https://my-demo.blog"
compile_sass = true
title = "after-dork theme"
description = ""
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "bfancy"
after_dork_menu = [
    {url = "$BASE_URL", name = "home"},
    {url = "$BASE_URL/categories", name = "categories"},
    {url = "$BASE_URL/tags", name = "tags"},
    {url = "$BASE_URL/archive", name = "archive"},
]
after_dork_title = "my demo blog"
