name = "after-dork"
description = "a robust, elegant d(a|o)rk theme"
license = "MIT"
homepage = "https://github.com/bfancy/after-dork"
min_version = "0.11.0"
demo = "https://bfan.cc/after-dork"

[extra]

[author]
name = "bfancy"
homepage = "https://github.com/bfancy"

[original]
author =  "after-dark"
homepage = "https://github.com/getzola/after-dark"
repo = "https://github.com/getzola/after-dark"
