name = "after-dork"
description = "A robust, elegant d(a|o)rk theme"
license = "MIT"
homepage = "https://github.com/gtfo/after-dork"
min_version = "0.1.0"
demo = "https://bfan.cc"

[extra]


[author]
name = "Duke"
homepage = "https://bfan.cc"

[original]
author =  "after-dark"
homepage = "https://github.com/getzola/after-dark"
repo = "https://github.com/getzola/after-dark"
